name = "satoori"
main = "worker.js"
compatibility_date = "2024-11-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[kv_namespaces]]
binding = "LEADERBOARD"
id = "a1fa04bf6f33476bae5f202af163e0bb"

